title: Ansible
description: A collection of ansible scripts
google_analytics: UA-50384518-5
show_downloads: true
theme: jekyll-theme-time-machine

gems:
  - jekyll-mentions

plugins:
  - jekyll-seo-tag
